### PR TITLE
Supporting axum 0.7

### PR DESCRIPTION
**Pull request by baptiste-le-m**
With the release of axum 0.7 there are some breaking changes (linked to the support of hyper v1)

### CODE REVIEW

**Comment by cdriehuys** [comment]
Am I reading this correctly in that this PR drops support for Axum versions below 0.7?

**Comment by baptiste-le-m** [comment]
Yes that's right. There are breaking change with the v0.7 of Axum
I am not sure how it would be possible to support both version ?

**Comment by baptiste-le-m** [comment]
Would you agree to merge this ? 
There is no hurry because this new axum version is brand new, but if no version of this lib supports version 0.7 it will make it impossible for users to upgrade

**Comment by cdriehuys** [comment]
Yes, I have no problem releasing a version of this library supporting Axum 0.7. I need to do some coordination with the other PR in progress right now to figure out if this should go in before or after that change.

**Comment by baptiste-le-m** [comment]
I see the other in progress PR has not moved for some time.
Also I don't think the other PR will conflict with this one.
I think it makes sense to merge this PR before the other one to avoid so that user can upgrade the lib to use axum 0.7 without having to migrate from `Jwks` to `KeyManager`. (but I understand that you could want the other way around like let people use the `KeyManager` feature without having to upgrade axum)

I understand that you have a busy schedule, and I appreciate the time you dedicate to the project.
If there are any additional changes or improvements needed in the pull request, please let me know. I'm more than willing to make any adjustments.

I am not sure if this is really a good idea, but I tried playing with the rust feature and was able (I think) to have both support for 0.6 and 0.7 https://github.com/cdriehuys/axum-jwks/pull/29

**Pull request merged**
