### PR TITLE
Support for more providers, support using openid-configuration

### PR DESCRIPTION
**Pull request by kjellkongsvik**
Thanks for a great crate, I like it!

This has been tested with:
 - AzureAD: e.g. https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration
 - https://github.com/navikt/mock-oauth2-server

I am very open to do modifications to this PR

### CODE REVIEW

**Comment by cdriehuys** [comment]
Thanks for the contribution. This looks good to me. Just so I understand, the only change to the existing API is that the JWKS URL has to include the "well known" portion now? And then the `from_oidc` methods are new?

**Comment by kjellkongsvik** [comment]
The function `from_authority` has been removed and replaced by
 - `from_jwks`, with the added argument `alg` and full path requirement. I think it is correct to rename this function.
 - `from_oidc`, with full path requirement. I am uncertain whether this should use the old name `from_authority`, I am open for that.

**Comment by cdriehuys** [comment]
Perhaps `from_url` would be a better name than `from_jwks`. To me, `from_jwks` implies we already have a JWKS object of some kind. What do you think?

**Comment by kjellkongsvik** [comment]
What about `from_jwks_url`? And `from_oidc_url` or `from_authority`?

**Comment by cdriehuys** [comment]
I like the `from_x_url` variants.

**Comment by cdriehuys** [comment]
Thanks again for the contribution! I'll try to cut a new release soon with these changes.

**Pull request merged**
